icam/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainapp.urls')),

    path('', include('pages.urls')),

    path('', include('record.urls')),

    path('', include('ilupt.urls')),

    path('', include('ruido.urls')),



]

#configuracion para cargar imagenes
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ilupt/urls.py
from django.urls import path
from . import views


urlpatterns = [
   path('evaluacion_iluminacion/<int:position_id>/', views.evaluacion_iluminacion, name='evaluacion_iluminacion'),
   
path('graph_day/<int:position_id>/', views.graph_day, name='graph_day'),
    path('graph_night/<int:position_id>/', views.graph_night, name='graph_night'),
]

record/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('puestos/',views.list,name="list_positions"),
    path('area/<int:area_id>',views.area,name="area"),
    path('puesto/<int:position_id>',views.position,name="position"),
    
    path('añadir-empresa/', views.add_company, name='add_company'),
    path('eliminar-empresa/<int:company_id>/', views.delete_company, name='delete_company'),
    path('editar-empresa/<int:company_id>/', views.edit_company, name='edit_company'),
    path('search-empresa/<int:user_id>/', views.search_company, name='search_company'),

    path('empresa/<int:company_id>/areas', views.company_areas, name='company_areas'),

    path('añadir-area/', views.add_area, name='add_area'),
    path('eliminar-area/<int:area_id>/', views.delete_area, name='delete_area'),
    path('editar-area/<int:area_id>/', views.edit_area, name='edit_area'),
    path('search-area/<int:company_id>/', views.search_area, name='search_area'),


    path('añadir-puesto/<int:area_id>/añadir-puesto/', views.add_position, name='add_position'),
    path('eliminar-puesto/<int:area_id>/puesto/<int:position_id>/eliminar/', views.delete_position, name='delete_position'),
    path('editar-puesto/<int:area_id>/puesto/<int:position_id>/editar/', views.edit_position, name='edit_position'),
    path('buscar-puesto/<int:area_id>/', views.search_position, name='search_position'),
    path('puestos/<int:area_id>/', views.puestos, name='puestos'),

]

ruido/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('evaluacion_ruido/<int:position_id>/', views.evaluacion_ruido, name='evaluacion_ruido'),
    # otras rutas...
]

ilupt/models.py
# Create your models here.
from django.db import models
from record.models import Position  # Make sure to import the Position model

class LightingEvaluation(models.Model):
    PERIOD_CHOICES = [
        ('Dia', 'Dia'),
        ('Noche', 'Noche'),
    ]
    TYPE_CHOICES = [
        ('Natural', 'Natural'),
        ('Artificial', 'Artificial'),
        ('Mixta', 'Mixta'),
    ]
    PARAMETER_CHOICES=[
        (50, '50'),
        (100, '100'),
        (300, '300'),
        (750, '750'),
        (3000, '3000+'),
    ]

    period = models.CharField(max_length=5, choices=PERIOD_CHOICES, verbose_name='Periodo')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, verbose_name='Tipo de Iluminación')    
    time = models.TimeField(verbose_name='Hora')

    left_1 = models.FloatField(null=True, blank=True, verbose_name='Izq1')
    left_2 = models.FloatField(null=True, blank=True, verbose_name='Izq2')
    left_3 = models.FloatField(null=True, blank=True, verbose_name='Izq3')
    left_4 = models.FloatField(null=True, blank=True, verbose_name='Izq4')
    left_5 = models.FloatField(null=True, blank=True, verbose_name='Izq5')

    center_1 = models.FloatField(null=True, blank=True, verbose_name='Cen1')
    center_2 = models.FloatField(null=True, blank=True, verbose_name='Cen2')
    center_3 = models.FloatField(null=True, blank=True, verbose_name='Cen3')
    center_4 = models.FloatField(null=True, blank=True, verbose_name='Cen4')
    center_5 = models.FloatField(null=True, blank=True, verbose_name='Cen5')
        
    right_1 = models.FloatField(null=True, blank=True, verbose_name='Der1')
    right_2 = models.FloatField(null=True, blank=True, verbose_name='Der2')
    right_3 = models.FloatField(null=True, blank=True, verbose_name='Der3')
    right_4 = models.FloatField(null=True, blank=True, verbose_name='Der4')
    right_5 = models.FloatField(null=True, blank=True, verbose_name='Der5')
 
    average = models.FloatField(verbose_name='Promedio')
    maximum = models.FloatField(verbose_name='Máximo')
    minimum = models.FloatField(verbose_name='Mínimo')

    parameter = models.IntegerField(choices=PARAMETER_CHOICES, verbose_name='Parámetro')
    date = models.DateField(verbose_name='Fecha')


    observations = models.TextField(null=True, blank=True, verbose_name='Observaciones')
    suggestions = models.TextField(null=True, blank=True, verbose_name='Sugerencias')

    # Here is the relationship with the Position model
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Posición')

ruido/models.py
from django.db import models
from record.models import Position  # Asegúrate de importar el modelo Position si es necesario

class RuidoEvaluation(models.Model):
   
    TYPE_CHOICES = [
        ('Estable', 'Estable'),
        ('Periodico', 'Tráfico'),
        ('Aletorio', 'Industrial'),
        ('Impacto', 'Impacto'),
    ]
    ANALYSIS_CHOICES = [
        ('Fija', 'Fija'),
        ('Movil', 'Movil'),
    ]

    type = models.CharField(max_length=10, choices=TYPE_CHOICES, verbose_name='Tipo de Ruido')
    source_type = models.CharField(max_length=10, choices=ANALYSIS_CHOICES, verbose_name='Tipo de Fuente')    
    date = models.DateField(verbose_name='Fecha')

    # Campos específicos para la evaluación del ruido
    min = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Mínimo')
    max = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Maximo')
    parameter = models.DecimalField(max_digits=6, decimal_places=2, default=85.00, verbose_name='LEP(*)')
    average = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='LAeqT')

    exposure_time = models.DecimalField(max_digits=3, decimal_places=2, default=0.0, verbose_name='TMPE (horas)')

    min_exposure_time = models.DecimalField(max_digits=3, decimal_places=2, default=0.0, verbose_name='TPE (horas)')
    dose = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name='Dosis')
    method = models.CharField(max_length=100, default='Medición del Nivel de Presión Acustica Continuo Equivalente Ponderado A', verbose_name='Metodo')
    
    # 25 variables de tipo decimal para mediciones de ruido
    m_1 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 1')
    m_2 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 2')
    m_3 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 3')
    m_4 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 4')
    m_5 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 5')
    m_6 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 6')
    m_7 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 7')
    m_8 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 8')
    m_9 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 9')
    m_10 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 10')
    m_11 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 11')
    m_12 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 12')
    m_13 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 13')
    m_14 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 14')
    m_15 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 15')
    m_16 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 16')
    m_17 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 17')
    m_18 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 18')
    m_19 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 19')
    m_20 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 20')
    m_21 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 21')
    m_22 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 22')
    m_23 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 23')
    m_24 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 24')
    m_25 = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name='Medición 25')

    observations = models.TextField(null=True, blank=True, verbose_name='Observaciones')
    suggestions = models.TextField(null=True, blank=True, verbose_name='Sugerencias')

    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Posición')
    
    def __str__(self):
        return f"Evaluación de Ruido para {self.position.name} en {self.date}"

record/forms.py
from django import forms
from .models import Position, Area

class PositionForm(forms.ModelForm):
    

    class Meta:
        model = Position
        fields = ['name', 'activity_type', 'image', 'public']

    

#formulario para agregar Area
class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        fields = ['name', 'description']

ruido/forms.py
from django import forms
from .models import RuidoEvaluation


class RuidoEvaluationForm(forms.ModelForm):
    class Meta:
        model = RuidoEvaluation
        exclude = ['position']  # Excluye el campo 'position' del formulario

        

ilupt/views.py
from django.shortcuts import render, redirect
from record.models import Position
from .forms import LightingEvaluationForm  # Asegúrate de importar tu formulario

def evaluacion_iluminacion(request, position_id):
    position = Position.objects.get(id=position_id)
    if request.method == 'POST':
        form = LightingEvaluationForm(request.POST)  # Crea una nueva instancia del formulario con los datos POST
        if form.is_valid():
            evaluation = form.save(commit=False)  # Crea una nueva instancia de LightingEvaluation pero no la guarda todavía
            evaluation.position = position  # Asigna el puesto de trabajo a la evaluación
            evaluation.save()  # Guarda la evaluación en la base de datos
            
            return redirect('position', position_id=position.id)  # Redirige a la página de detalle del puesto de trabajo
        else:
            print(form.errors)
    else:
        form = LightingEvaluationForm()  # Crea una nueva instancia del formulario vacía
    context = {'position': position, 'form': form}
    return render(request, 'evaluacion_iluminacion.html', context)


#grafico
from django.http import HttpResponse
import matplotlib.pyplot as plt
from record.models import Position
from matplotlib.dates import YearLocator
import numpy as np
def graph_day(request, position_id):
    # Obtén las evaluaciones para el puesto de trabajo
    evaluations = Position.objects.get(id=position_id).lightingevaluation_set.filter(period="Dia").order_by('date')

    # Crea una figura y un eje con fondo transparente
    fig, ax = plt.subplots()
    fig.patch.set_alpha(0)
    ax.set_facecolor('darkblue')

    # Extrae los años y los promedios de las evaluaciones
    years = [evaluation.date.year for evaluation in evaluations]
    averages = [evaluation.average for evaluation in evaluations]
    parameters = [evaluation.parameter for evaluation in evaluations]

    # Crea el gráfico de barras
    bars = ax.bar(years, averages, color='orange', edgecolor='white', label='Promedio')

    # Añade la línea del parámetro al final
    parameter = parameters[0] if len(parameters) == 1 else parameters[-1]
    ax.hlines(y=parameter, xmin=min(years)-1, xmax=max(years)+1, colors='white', linestyles='--', linewidth=2.0, label='Parámetro')

    ax.legend()

    # Añade títulos y etiquetas
    ax.set_title('Fluctuación del promedio de las evaluaciones de día', color='white')
    ax.set_xlabel('Año', color='white')
    ax.set_ylabel('Valor', color='white')

    # Configura el eje x para mostrar solo los años
    ax.set_xticks(years)
    ax.set_xticklabels(years, color='white')

    # Cambia el color de los ejes a blanco
    ax.spines['bottom'].set_color('white')
    ax.spines['top'].set_color('white') 
    ax.spines['right'].set_color('white')
    ax.spines['left'].set_color('white')

    ax.xaxis.label.set_color('white')
    ax.tick_params(axis='x', colors='white')

    ax.yaxis.label.set_color('white')
    ax.tick_params(axis='y', colors='white')

    # Añade el año debajo de cada barra
    for year, bar in zip(years, bars):
        ax.text(bar.get_x() + bar.get_width()/2, -0.05, year, ha='center', va='bottom', color='white')

    # Crea un objeto HttpResponse con el tipo de contenido correcto
    response = HttpResponse(content_type='image/png')

    # Guarda la figura en el objeto HttpResponse
    fig.savefig(response, format='png', transparent=True)

    return response

def graph_night(request, position_id):
    # Obtén las evaluaciones para el puesto de trabajo
    evaluations = Position.objects.get(id=position_id).lightingevaluation_set.filter(period="Noche").order_by('date')

    # Crea una figura y un eje con fondo transparente
    fig, ax = plt.subplots()
    fig.patch.set_alpha(0)
    ax.set_facecolor('darkblue')

    # Extrae los años y los promedios de las evaluaciones
    years = [evaluation.date.year for evaluation in evaluations]
    averages = [evaluation.average for evaluation in evaluations]
    parameters = [evaluation.parameter for evaluation in evaluations]

    # Crea el gráfico de barras
    bars = ax.bar(years, averages, color='orange', edgecolor='white', label='Promedio')

    # Añade la línea del parámetro al final
    parameter = parameters[0] if len(parameters) == 1 else parameters[-1]
    ax.hlines(y=parameter, xmin=min(years)-1, xmax=max(years)+1, colors='white', linestyles='--', linewidth=2.0, label='Parámetro')

    ax.legend()

    # Añade títulos y etiquetas
    ax.set_title('Fluctuación del promedio de las evaluaciones de noche', color='white')
    ax.set_xlabel('Año', color='white')
    ax.set_ylabel('Valor', color='white')

    # Configura el eje x para mostrar solo los años
    ax.set_xticks(years)
    ax.set_xticklabels(years, color='white')

    # Cambia el color de los ejes a blanco
    ax.spines['bottom'].set_color('white')
    ax.spines['top'].set_color('white') 
    ax.spines['right'].set_color('white')
    ax.spines['left'].set_color('white')

    ax.xaxis.label.set_color('white')
    ax.tick_params(axis='x', colors='white')

    ax.yaxis.label.set_color('white')
    ax.tick_params(axis='y', colors='white')

    # Añade el año debajo de cada barra
    for year, bar in zip(years, bars):
        ax.text(bar.get_x() + bar.get_width()/2, -0.05, year, ha='center', va='bottom', color='white')

    # Crea un objeto HttpResponse con el tipo de contenido correcto
    response = HttpResponse(content_type='image/png')

    # Guarda la figura en el objeto HttpResponse
    fig.savefig(response, format='png', transparent=True)

    return response

ruido/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RuidoEvaluationForm
from record.models import Position

def evaluacion_ruido(request, position_id):
    position = get_object_or_404(Position, id=position_id)
    
    if request.method == 'POST':
        form = RuidoEvaluationForm(request.POST)
        print(request.POST)  # Imprime los datos POST para depuración
        if form.is_valid():
            evaluation = form.save(commit=False)
            evaluation.position = position
            evaluation.save()
            print("Datos guardados correctamente.")  # Mensaje de éxito
            return redirect('position', position_id=position.id)
        else:
            print(form.errors)  # Imprime los errores del formulario para depuración
            context = {'position': position, 'form': form}
            return render(request, 'evaluacion_ruido.html', context)
    else:
        form = RuidoEvaluationForm()

    context = {'position': position, 'form': form}
    return render(request, 'evaluacion_ruido.html', context)

record/templates/evaluations/ilu_pt.html
<button id="toggleAllEvaluationsButton" style="background-color: orange; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border: none; border-radius: 12px;">
    <i class="fas fa-angle-down"></i> Mostrar/Ocultar Evaluaciones ILUMINACION
</button>

<div id="evaluationspt">

<h2>Evaluaciones de Iluminación</h2>
<button id="toggleDayEvaluationsButton">Mostrar/Ocultar Evaluaciones de Día</button>
<button id="toggleNightEvaluationsButton">Mostrar/Ocultar Evaluaciones de Noche</button>
    
    
    <div id="dayEvaluations">
        <h3>Periodo Dia</h3>

    {% for evaluation in lighting_evaluations|dictsort:"date" %}
        {% if evaluation.period == "Dia" %}
            <div class="evaluation">

                <div class="evaluation-box">
          
                    <table class="styled-table">
                        <tr>
                            <th rowspan="2">Fecha</th>
                            <th rowspan="2">Tipo de Iluminacion</th>
                            <th rowspan="2">Hora</th>
                            <th colspan="3">Mediciones</th>
                            <th rowspan="2">Max</th>
                            <th rowspan="2">Min</th>
                            <th rowspan="2">Promedio</th>
                            <th rowspan="2">Parámetro</th>
                            <th rowspan="2">Cumplimiento</th>
            
                            {% if evaluation.observations %}
                            <th rowspan="2">Observación</th>
                            {% endif %}
                            
                            {% if evaluation.suggestions %}
                            <th rowspan="2">Sugerencias</th>
                            {% endif %}
                        </tr>
                        <tr>
                            <th>Izq.</th>
                            <th>Cen.</th>
                            <th>Der.</th>
                        </tr>
                        <tr>
                            <td rowspan="5">{{ evaluation.date |date:"d/m/Y"}}</td>
                            <td rowspan="5">{{ evaluation.type }}</td>
                            <td rowspan="5">{{ evaluation.time }}</td>
                            <td>{{ evaluation.left_1 }}</td>
                            <td>{{ evaluation.center_1 }}</td>
                            <td>{{ evaluation.right_1 }}</td>
                            <td rowspan="5">{{ evaluation.maximum }}</td>
                            <td rowspan="5">{{ evaluation.minimum }}</td>
                            <td rowspan="5">{{ evaluation.average }}</td>
                            <td rowspan="5">{{ evaluation.parameter }}</td>
                            <td rowspan="5">{% if evaluation.average > evaluation.parameter %}Cumple{% else %}No cumple{% endif %}</td>
                            
                            {% if evaluation.observations %}
                            <td rowspan="5">{{ evaluation.observations }}</td>
                            {% endif %}
            
                            {% if evaluation.suggestions %}
                            <td rowspan="5">{{ evaluation.suggestions }}</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td>{{ evaluation.left_2 }}</td>
                            <td>{{ evaluation.center_2 }}</td>
                            <td>{{ evaluation.right_2 }}</td>
                        </tr>
                        <tr>
                            <td>{{ evaluation.left_3 }}</td>
                            <td>{{ evaluation.center_3 }}</td>
                            <td>{{ evaluation.right_3 }}</td>
                        </tr>
                        <tr>
                            <td>{{ evaluation.left_4 }}</td>
                            <td>{{ evaluation.center_4 }}</td>
                            <td>{{ evaluation.right_4 }}</td>
                        </tr>
                        <tr>
                            <td>{{ evaluation.left_5 }}</td>
                            <td>{{ evaluation.center_5 }}</td>
                            <td>{{ evaluation.right_5 }}</td>
                        </tr>
                    </table>
                </div>               
             </div>
        {% endif %}
    {% endfor %}
    <img src="{% url 'graph_day' position.id %}" alt="Gráfico de día">

    </div>

    <div id="nightEvaluations">
        <h3>Evaluación de Noche</h3>
    {% for evaluation in lighting_evaluations|dictsort:"date" %}
        {% if evaluation.period == "Noche" %}
            <div class="evaluation">
                    
    <div class="evaluation-box">
            
        <table class="styled-table">
            <tr>
                <th rowspan="2">Fecha</th>
                <th rowspan="2">Tipo de Iluminacion</th>
                <th rowspan="2">Hora</th>
                <th colspan="3">Mediciones</th>
                <th rowspan="2">Max</th>
                <th rowspan="2">Min</th>
                <th rowspan="2">Promedio</th>
                <th rowspan="2">Parámetro</th>
                <th rowspan="2">Cumplimiento</th>

                {% if evaluation.observations %}
                <th rowspan="2">Observación</th>
                {% endif %}
                
                {% if evaluation.suggestions %}
                <th rowspan="2">Sugerencias</th>
                {% endif %}
            </tr>
            <tr>
                <th>Izq.</th>
                <th>Cen.</th>
                <th>Der.</th>
            </tr>
            <tr>
                <td rowspan="5">{{ evaluation.date |date:"d/m/Y"}}</td>
                <td rowspan="5">{{ evaluation.type }}</td>
                <td rowspan="5">{{ evaluation.time }}</td>
                <td>{{ evaluation.left_1 }}</td>
                <td>{{ evaluation.center_1 }}</td>
                <td>{{ evaluation.right_1 }}</td>
                <td rowspan="5">{{ evaluation.maximum }}</td>
                <td rowspan="5">{{ evaluation.minimum }}</td>
                <td rowspan="5">{{ evaluation.average }}</td>
                <td rowspan="5">{{ evaluation.parameter }}</td>
                <td rowspan="5">{% if evaluation.average > evaluation.parameter %}Cumple{% else %}No cumple{% endif %}</td>
                
                {% if evaluation.observations %}
                <td rowspan="5">{{ evaluation.observations }}</td>
                {% endif %}

                {% if evaluation.suggestions %}
                <td rowspan="5">{{ evaluation.suggestions }}</td>
                {% endif %}
            </tr>
            <tr>
                <td>{{ evaluation.left_2 }}</td>
                <td>{{ evaluation.center_2 }}</td>
                <td>{{ evaluation.right_2 }}</td>
            </tr>
            <tr>
                <td>{{ evaluation.left_3 }}</td>
                <td>{{ evaluation.center_3 }}</td>
                <td>{{ evaluation.right_3 }}</td>
            </tr>
            <tr>
                <td>{{ evaluation.left_4 }}</td>
                <td>{{ evaluation.center_4 }}</td>
                <td>{{ evaluation.right_4 }}</td>
            </tr>
            <tr>
                <td>{{ evaluation.left_5 }}</td>
                <td>{{ evaluation.center_5 }}</td>
                <td>{{ evaluation.right_5 }}</td>
            </tr>
        </table>
    </div><!-- Aquí puedes mostrar los demás campos de la evaluación -->
</div>    
            {% endif %}
        {% endfor %}
        <img src="{% url 'graph_night' position.id %}" alt="Gráfico de noche">

        
    </div>

    

<script>
document.getElementById('toggleAllEvaluationsButton').addEventListener('click', function() {
    var evaluations = document.getElementById('evaluationspt');
    if (evaluations.style.display === 'none') {
        evaluations.style.display = 'block';
    } else {
        evaluations.style.display = 'none';
    }
});

document.getElementById('toggleDayEvaluationsButton').addEventListener('click', function() {
    var dayEvaluations = document.getElementById('dayEvaluations');
    if (dayEvaluations.style.display === 'none') {
        dayEvaluations.style.display = 'block';
    } else {
        dayEvaluations.style.display = 'none';
    }
});

document.getElementById('toggleNightEvaluationsButton').addEventListener('click', function() {
    var nightEvaluations = document.getElementById('nightEvaluations');
    if (nightEvaluations.style.display === 'none') {
        nightEvaluations.style.display = 'block';
    } else {
        nightEvaluations.style.display = 'none';
    }
});
</script>

record/templates/evaluations/ruido.html
<!-- Evaluaciones de Ruido -->
    <button id="toggleAllRuidoEvaluationsButton" style="background-color: orange; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border: none; border-radius: 12px;">
        <i class="fas fa-angle-down"></i> Mostrar/Ocultar Evaluaciones RUIDO
    </button>
    <div id="ruidoEvaluations">
        <h2>Evaluaciones de Ruido</h2>
        {% for evaluation in ruido_evaluations %}
            <div class="evaluation">
                <h3>Evaluación realizada el {{ evaluation.date }}</h3>
                <p><strong>Tipo de Ruido:</strong> {{ evaluation.get_type_display }}</p>
                <p><strong>Tipo de Fuente:</strong> {{ evaluation.get_source_type_display }}</p>
                <p><strong>Mínimo:</strong> {{ evaluation.min }}</p>
                <p><strong>Máximo:</strong> {{ evaluation.max }}</p>
                <p><strong>Promedio:</strong> {{ evaluation.average }}</p>
                <p><strong>Parametro:</strong> {{ evaluation.parameter }}</p>

                <!-- Agrega el resto de los campos que quieres mostrar -->
            </div>
        {% endfor %}
    </div>
<script>
    document.getElementById('toggleAllRuidoEvaluationsButton').addEventListener('click', function() {
        var ruidoEvaluations = document.getElementById('ruidoEvaluations');
        if (ruidoEvaluations.style.display === 'none') {
            ruidoEvaluations.style.display = 'block';
        } else {
            ruidoEvaluations.style.display = 'none';
        }
    });
</script>